service: slack-jobcan
frameworkVersion: '3'

package:
  individually: true
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node14'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10
    watch:
      pattern: ['src/**/*.ts'] # match only typescript files in src directory
      ignore: ['temp/**/*']

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_USERNAME: ${env:GITHUB_USERNAME}
    GITHUB_REPO: ${env:GITHUB_REPO}
functions:
  slack:
    handler: src/handler.handler
    events:
      - http:
          path: slack/events
          method: post
useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-offline